# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

QT += webenginewidgets
TEMPLATE = app
TARGET = HoYoLAB Desktop
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += GeneratedFiles/$(ConfigurationName)
OBJECTS_DIR += debug
UI_DIR += GeneratedFiles
RCC_DIR += GeneratedFiles
include(HoYoLAB Desktop.pri)
win32:RC_FILE = HoYoLAB Desktop.rc
